apiVersion: v1 # Uses the core Kubernetes API group (v1)
kind: PersistentVolumeClaim # Declares this manifest as a PVC (PersistentVolumeClaim)
metadata: # Metadata section
  name: mysql-database-storage # Name of the PVC → "mysql-database-storage"
spec: # Specification of the claim (desired storage characteristics)
  resources: # Resource requirements
    requests: # What this PVC is requesting from a PV
      storage: 50Mi # Requesting 50Mi (megabytes) of storage
  accessModes: # Defines how the volume can be mounted by Pods
    - ReadWriteMany # Volume can be mounted read-write by many nodes/Pods at the same time
  volumeName: mysql-persistent-volume # Explicitly binds this claim to a PersistentVolume named "mysql-persistent-volume"
