apiVersion: apps/v1 # Uses the apps/v1 API group (for controllers like Deployment)
kind: Deployment # Declares this manifest as a Deployment resource
metadata: # Metadata section
  name: nginx-web-nodename-deployment # Name of the Deployment
spec: # Specification of the Deployment
  replicas: 1 # Desired number of Pod replicas
  selector: # Defines how to identify the Pods managed by this Deployment
    matchLabels: # Labels to match
      app: nginx-web-nodename # Must match Pods with this label
  template: # Template for creating Pods
    metadata: # Metadata for the Pod template
      labels: # Labels applied to created Pods
        app: nginx-web-nodename # Label must match selector above
    spec: # Pod specification (like a normal Pod manifest)
      containers: # List of containers in the Pod
        - name: nginx-web-container # Container name
          image: nginx:latest # Docker image to use
          ports: # Ports exposed by the container
            - containerPort: 80 # nginx default HTTP port
      nodeName: "k8s-class-worker1" # Forces Pod to run on specific node (bypasses scheduler)
